import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User.js';
import Product from './models/Product.js';
import Category from './models/Category.js';
import connectDB from './config/db.js';

dotenv.config();

connectDB();

const importData = async () => {
  try {
    await Category.deleteMany();
    await Product.deleteMany();
    await User.deleteMany();

    const createdCategories = await Category.insertMany([
      { name: 'cricket', description: 'All cricket gear', image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=400' },
      { name: 'football', description: 'Everything for soccer', image: 'https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&q=80&w=400' },
      { name: 'gym', description: 'Weightlifting and fitness', image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=400' },
      { name: 'trophy', description: 'Awards, medals, and premium trophies to celebrate victories and achievements.', image: '/trophy_cup.png' }
    ]);

    const adminUser = await User.create({
      name: 'Admin User',
      email: process.env.ADMIN_EMAIL || 'admin@example.com',
      password: process.env.ADMIN_PASSWORD || 'password123',
      isAdmin: true,
    });

    const cricket = createdCategories[0]._id;
    const football = createdCategories[1]._id;
    const gym = createdCategories[2]._id;
    const trophy = createdCategories[3]._id;

    const products = [
      // ─────────────── CRICKET (12 products) ───────────────
      {
        name: 'Pro English Willow Cricket Bat',
        images: ['/products/cricket_bat.png'],
        description: 'Premium grade 1 English willow cricket bat with huge edges and perfect balance. Match ready. Comes with factory-fitted toe guard and fully knocked-in. Ideal for power hitters who demand explosive performance in every shot.',
        brand: 'SK Sports',
        category: cricket,
        price: 120.00,
        countInStock: 5,
        rating: 4.5,
        numReviews: 12,
      },
      {
        name: 'Premium Titanium Cricket Helmet',
        images: ['/products/premium_cricket_helmet.png'],
        description: 'High protection titanium grille helmet with supreme comfort and ventilation, perfect for long innings. Steel grille tested to BS7928:2013 standard. Adjustable inner foam padding for a custom fit.',
        brand: 'SK Sports',
        category: cricket,
        price: 75.00,
        countInStock: 10,
        rating: 4.8,
        numReviews: 24,
      },
      {
        name: 'Professional Leather Cricket Ball',
        images: ['/products/cricket_ball.png'],
        description: 'Alum tanned leather cricket ball tailored for club matches. Exceptional seam and shape retention. Four piece construction, hand-stitched with a prominent seam for late swing and sharp movement.',
        brand: 'SK Sports',
        category: cricket,
        price: 25.00,
        countInStock: 50,
        rating: 4.2,
        numReviews: 18,
      },
      {
        name: 'Cricket Batting Pads (Junior)',
        images: ['/products/cricket_pads.png'],
        description: 'Lightweight junior batting pads crafted for young cricketers. High density foam bolsters offer maximum protection without restricting movement. Velcro strap system for secure fit.',
        brand: 'SK Sports',
        category: cricket,
        price: 45.00,
        countInStock: 18,
        rating: 4.3,
        numReviews: 9,
      },
      {
        name: 'Cricket Batting Gloves Pro',
        images: ['/products/cricket_batting_gloves.png'],
        description: 'Tournament-grade batting gloves with full sheepskin palm, multi-piece finger protection and snug wrist strap. Excellent feel with superior protection on both hands.',
        brand: 'SK Sports',
        category: cricket,
        price: 38.00,
        countInStock: 22,
        rating: 4.6,
        numReviews: 31,
      },
      {
        name: 'Cricket Wicket Keeping Gloves',
        images: ['/products/cricket_wk_gloves.png'],
        description: 'Pro-spec wicket keeping gloves with oversized sausage fingers and inners for unparalleled catching grip. Extended palm for maximum surface coverage.',
        brand: 'SK Sports',
        category: cricket,
        price: 55.00,
        countInStock: 14,
        rating: 4.4,
        numReviews: 7,
      },
      {
        name: 'Stump Set with Bails (Full Size)',
        images: ['/cricket_stumps.png'],
        description: 'Regulation-size cricket stumps made of high-grade ash wood, complete with metal base spikes and UV-resistant painted finish. Set of 6 stumps and 4 bails.',
        brand: 'SK Sports',
        category: cricket,
        price: 30.00,
        countInStock: 30,
        rating: 4.1,
        numReviews: 15,
      },
      {
        name: 'Cricket Kit Bag – Wheelie',
        images: ['https://images.unsplash.com/photo-1709729987890-4a09e04c6e30?auto=format&fit=crop&q=80&w=800'],
        description: 'Massive capacity cricket wheelie bag with separate bat cavity (fits 4 bats), padded helmet pocket, shoe compartment and waterproof base. Smooth-rolling wheels for easy transport.',
        brand: 'SK Sports',
        category: cricket,
        price: 90.00,
        countInStock: 8,
        rating: 4.7,
        numReviews: 19,
      },
      {
        name: 'Cricket Bowling Machine Balls (6-Pack)',
        images: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&q=80&w=800'],
        description: 'Specially moulded 2-piece balls compatible with all standard bowling machines. Durable polyurethane construction for consistent swing and seam behaviour across hundreds of deliveries.',
        brand: 'SK Sports',
        category: cricket,
        price: 22.00,
        countInStock: 60,
        rating: 4.0,
        numReviews: 11,
      },
      {
        name: 'Cotton Cricket Whites Trouser',
        images: ['https://images.unsplash.com/photo-1624952040545-dfe94ed9fc49?auto=format&fit=crop&q=80&w=800'],
        description: 'Professional white cricket trousers in breathable 100% cotton fabric. Elasticised waistband and traditional side pockets. Available in all sizes.',
        brand: 'SK Sports',
        category: cricket,
        price: 28.00,
        countInStock: 40,
        rating: 4.3,
        numReviews: 8,
      },
      {
        name: 'Cricket Abdominal Guard',
        images: ['https://images.unsplash.com/photo-1576678927484-cc907957088c?auto=format&fit=crop&q=80&w=800'],
        description: 'High-density hard-shell abdominal guard with a comfortable moisture-wicking inner liner. Lightweight and secure elastic waistband integration.',
        brand: 'SK Sports',
        category: cricket,
        price: 15.00,
        countInStock: 35,
        rating: 4.5,
        numReviews: 20,
      },
      {
        name: 'Cricket Spike Shoes – Rubber Sole',
        images: ['https://images.unsplash.com/photo-1571895954609-1da2f23dcaa0?auto=format&fit=crop&q=80&w=800'],
        description: 'Lightweight cricket shoes with rubber spike sole for excellent grip on dry pitches. Breathable mesh upper and reinforced toe box for durability.',
        brand: 'SK Sports',
        category: cricket,
        price: 65.00,
        countInStock: 20,
        rating: 4.6,
        numReviews: 16,
      },

      // ─────────────── FOOTBALL (11 products) ───────────────
      {
        name: 'Premium Match Football Size 5',
        images: ['https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&q=80&w=800'],
        description: 'Professional match ball with excellent shape retention and flight accuracy. FIFA Quality Pro tested. Thermal bonded 32-panel construction for optimal aerodynamics.',
        brand: 'SK Sports',
        category: football,
        price: 40.00,
        countInStock: 15,
        rating: 5,
        numReviews: 8,
      },
      {
        name: 'Elite Pro Goalkeeper Gloves',
        images: ['/gk_gloves.png'],
        description: 'Premium professional goalkeeper gloves featuring excellent grip padding and neon green accents. Negative cut for a tighter, more precise fit. Flat palm latex for maximum ball contact.',
        brand: 'SK Sports',
        category: football,
        price: 35.00,
        countInStock: 25,
        rating: 4.7,
        numReviews: 14,
      },
      {
        name: 'Agility Training Cones & Ladder Set',
        images: ['/agility_set.png'],
        description: 'Complete football agility training set including 20 orange cones and a 6m agility ladder, perfectly engineered for speed and directional change drills.',
        brand: 'SK Sports',
        category: football,
        price: 25.00,
        countInStock: 40,
        rating: 4.8,
        numReviews: 32,
      },
      {
        name: 'Professional Football Boots – Firm Ground',
        images: ['https://images.unsplash.com/photo-1511886929837-354d827aae26?auto=format&fit=crop&q=80&w=800'],
        description: 'Firm ground football boots with a precision knit upper for ball control and a conical stud configuration for multi-directional traction on natural grass pitches.',
        brand: 'SK Sports',
        category: football,
        price: 85.00,
        countInStock: 20,
        rating: 4.6,
        numReviews: 26,
      },
      {
        name: 'Football Shin Guards Pro',
        images: ['https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800'],
        description: 'Anatomically shaped hard-shell shin guards with an EVA foam backing. Secure sock-sleeve application for a precise, slip-resistant fit throughout the game.',
        brand: 'SK Sports',
        category: football,
        price: 18.00,
        countInStock: 50,
        rating: 4.4,
        numReviews: 42,
      },
      {
        name: 'Football Training Bibs (Set of 10)',
        images: ['https://images.unsplash.com/photo-1617083934551-ac1ef7db8dd0?auto=format&fit=crop&q=80&w=800'],
        description: 'Pack of 10 lightweight mesh bibs in 5 different colours, ideal for team training sessions. Machine washable polyester, one-size-fits-all.',
        brand: 'SK Sports',
        category: football,
        price: 20.00,
        countInStock: 30,
        rating: 4.2,
        numReviews: 17,
      },
      {
        name: 'Pop-Up Football Goal (Pair)',
        images: ['https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&q=80&w=800'],
        description: 'Pair of portable pop-up football goals with fibreglass frame and heavy-duty net. Sets up in seconds, folds flat for easy storage and transport.',
        brand: 'SK Sports',
        category: football,
        price: 55.00,
        countInStock: 12,
        rating: 4.5,
        numReviews: 22,
      },
      {
        name: 'Football Rebounder Net',
        images: ['https://images.unsplash.com/photo-1585247226801-bc613c441316?auto=format&fit=crop&q=80&w=800'],
        description: 'Steel-framed rebounder net ideal for solo passing and shooting practice. Adjustable angle settings return the ball at different trajectories. Foldable design.',
        brand: 'SK Sports',
        category: football,
        price: 70.00,
        countInStock: 10,
        rating: 4.7,
        numReviews: 13,
      },
      {
        name: 'Speed & Resistance Training Parachute',
        images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=800'],
        description: 'Sprint resistance parachute for explosive speed training. Nylon chute, adjustable waist harness and quick-release buckle for safe use during intervals.',
        brand: 'SK Sports',
        category: football,
        price: 22.00,
        countInStock: 28,
        rating: 4.3,
        numReviews: 19,
      },
      {
        name: 'Football Ankle Support Brace',
        images: ['https://images.unsplash.com/photo-1535743686920-55e4145369b9?auto=format&fit=crop&q=80&w=800'],
        description: 'Low-profile lace-up ankle brace providing medial and lateral stability without limiting natural motion. Breathable mesh sides, fits inside boots.',
        brand: 'SK Sports',
        category: football,
        price: 16.00,
        countInStock: 45,
        rating: 4.5,
        numReviews: 38,
      },
      {
        name: 'Football Compression Socks',
        images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&q=80&w=800'],
        description: 'Graduated compression football socks that improve circulation and reduce muscle fatigue. Cushioned sole, reinforced heel and anti-blister lining.',
        brand: 'SK Sports',
        category: football,
        price: 12.00,
        countInStock: 60,
        rating: 4.4,
        numReviews: 29,
      },

      // ─────────────── GYM (11 products) ───────────────
      {
        name: 'Adjustable Dumbbells Set',
        images: ['https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&q=80&w=800'],
        description: 'Versatile 2–24kg adjustable dumbbell set for a complete home gym experience. Quick-select dial mechanism, rubber end caps and space-saving design replace 15 pairs of traditional dumbbells.',
        brand: 'FlexFit',
        category: gym,
        price: 199.99,
        countInStock: 8,
        rating: 4.8,
        numReviews: 34,
      },
      {
        name: 'Yoga Mat with Alignment Lines',
        images: ['/yoga_mat_alignment.png'],
        description: 'Eco-friendly non-slip yoga mat with alignment marks. 6mm thick TPE foam provides optimal cushioning for joints. Carries strap and carrying bag included.',
        brand: 'EcoZen',
        category: gym,
        price: 35.00,
        countInStock: 20,
        rating: 4.9,
        numReviews: 54,
      },
      {
        name: 'Olympic Barbell 20kg',
        images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800'],
        description: 'Competition grade 20kg Olympic barbell with chrome finish, dual knurling marks and 220kg weight capacity. Standard 50mm sleeve diameter. Ideal for squats, bench press and deadlifts.',
        brand: 'PowerCraft',
        category: gym,
        price: 150.00,
        countInStock: 6,
        rating: 4.7,
        numReviews: 21,
      },
      {
        name: 'Rubber Weight Plates Set (20kg)',
        images: ['https://images.unsplash.com/photo-1606889464198-fcb3e86f9b47?auto=format&fit=crop&q=80&w=800'],
        description: 'Solid rubber encased 20kg weight plate set (2×1.25kg, 2×2.5kg, 2×5kg, 2×10kg). Colour-coded by weight, with easy grip handles and 50mm centre bore.',
        brand: 'PowerCraft',
        category: gym,
        price: 80.00,
        countInStock: 15,
        rating: 4.6,
        numReviews: 17,
      },
      {
        name: 'Pull-Up & Dip Bar Station',
        images: ['https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&q=80&w=800'],
        description: 'Free-standing pull-up and dip bar station with a 150kg load capacity. Multi-grip handles (wide, neutral, narrow), foam-padded grips and non-slip rubber feet.',
        brand: 'FlexFit',
        category: gym,
        price: 120.00,
        countInStock: 5,
        rating: 4.8,
        numReviews: 28,
      },
      {
        name: 'Resistance Bands Set (5 Levels)',
        images: ['https://images.unsplash.com/photo-1598266663439-2056e6900339?auto=format&fit=crop&q=80&w=800'],
        description: 'Set of 5 loop resistance bands ranging from 5–125 lbs. Natural latex construction, perfect for warm-up, rehabilitation, assisted pull-ups and strength training.',
        brand: 'EcoZen',
        category: gym,
        price: 25.00,
        countInStock: 40,
        rating: 4.7,
        numReviews: 63,
      },
      {
        name: 'Jump Rope – Speed Cable',
        images: ['https://images.unsplash.com/photo-1607962837359-5e7e89f86776?auto=format&fit=crop&q=80&w=800'],
        description: 'Bearing-equipped speed cable jump rope with PVC-coated 3mm cable. Adjustable length up to 3m, ergonomic non-slip handles. Ideal for CrossFit, boxing and cardio work.',
        brand: 'SK Sports',
        category: gym,
        price: 15.00,
        countInStock: 50,
        rating: 4.5,
        numReviews: 47,
      },
      {
        name: 'Foam Roller – Deep Tissue',
        images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800'],
        description: '60cm high-density EPP foam roller with grid surface for targeted deep tissue massage and myofascial release. Supports up to 150kg, durable and hollow for storage.',
        brand: 'EcoZen',
        category: gym,
        price: 28.00,
        countInStock: 25,
        rating: 4.6,
        numReviews: 39,
      },
      {
        name: 'Weightlifting Gloves with Wrist Wrap',
        images: ['https://images.unsplash.com/photo-1581009137042-c552e485697a?auto=format&fit=crop&q=80&w=800'],
        description: 'Full palm gym gloves with integrated 30cm neoprene wrist wrap support. Micro-fibre palm padding, ventilated mesh back and double-stitched long life construction.',
        brand: 'FlexFit',
        category: gym,
        price: 22.00,
        countInStock: 35,
        rating: 4.4,
        numReviews: 55,
      },
      {
        name: 'Ab Roller Wheel with Knee Pad',
        images: ['https://images.unsplash.com/photo-1544216717-3bbf52512659?auto=format&fit=crop&q=80&w=800'],
        description: 'Dual-wheel ab roller with extra-wide 3.2-inch wheels for superior lateral stability. Ergonomic soft-grip handles and thick foam knee pad included.',
        brand: 'FlexFit',
        category: gym,
        price: 18.00,
        countInStock: 30,
        rating: 4.5,
        numReviews: 43,
      },
      {
        name: 'Gym Shaker Bottle 700ml',
        images: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800'],
        description: '700ml BPA-free protein shaker bottle with stainless steel blending ball, measurement markings and secure leak-proof lid. Dishwasher safe.',
        brand: 'SK Sports',
        category: gym,
        price: 10.00,
        countInStock: 80,
        rating: 4.3,
        numReviews: 71,
      },

      // ─────────────── TROPHY (10 products) ───────────────
      {
        name: 'Premium Gold Cup Trophy',
        images: ['/trophy_cup.png'],
        description: 'A beautiful, highly detailed premium gold cup trophy on a prestigious wooden base. Die-cast metal construction with UV-cured gold plating. Perfect for tournament champions.',
        brand: 'SK Awards',
        category: trophy,
        price: 85.00,
        countInStock: 50,
        rating: 5.0,
        numReviews: 12,
      },
      {
        name: 'Crystal Glass Shield Award',
        images: ['https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&q=80&w=800'],
        description: 'Stunning optically clear crystal glass shield award, laser engraved to order. Comes presented in a black satin-lined gift box with free personalised engraving up to 50 characters.',
        brand: 'SK Awards',
        category: trophy,
        price: 60.00,
        countInStock: 30,
        rating: 4.8,
        numReviews: 9,
      },
      {
        name: 'Sports Star Acrylic Trophy',
        images: ['https://images.unsplash.com/photo-1611068786591-ec90bec1ae9c?auto=format&fit=crop&q=80&w=800'],
        description: '5mm thick star-shaped acrylic award in vibrant blue. Engraved via laser etching. Supplied in gift box. Ideal for "Player of the Match" and outstanding performance awards.',
        brand: 'SK Awards',
        category: trophy,
        price: 25.00,
        countInStock: 60,
        rating: 4.5,
        numReviews: 18,
      },
      {
        name: 'Gold Medal Set (Pack of 10)',
        images: ['https://images.unsplash.com/photo-1523289333742-be1143f6b766?auto=format&fit=crop&q=80&w=800'],
        description: 'Pack of 10 gold-plated zinc alloy medals on an 80cm ribbon. Diameter 60mm with generic laurel wreath design. Suitable for all sports. Text engraving available.',
        brand: 'SK Awards',
        category: trophy,
        price: 35.00,
        countInStock: 100,
        rating: 4.4,
        numReviews: 24,
      },
      {
        name: 'Silver Salver Tray Trophy',
        images: ['https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=800'],
        description: '25cm silver-plated salver award with traditional gadroon border. Engraving area in centre. Supplied in presentation box. Ideal for golf, cricket and snooker awards.',
        brand: 'SK Awards',
        category: trophy,
        price: 55.00,
        countInStock: 20,
        rating: 4.7,
        numReviews: 7,
      },
      {
        name: 'Perpetual Wooden Plaque',
        images: ['https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&q=80&w=800'],
        description: 'Solid walnut wood perpetual plaque with 20 gold-engraved name plates, ideal for annual club champion awards. Wall mounting kit included.',
        brand: 'SK Awards',
        category: trophy,
        price: 95.00,
        countInStock: 15,
        rating: 4.9,
        numReviews: 5,
      },
      {
        name: 'Resin Footballer Figure Trophy',
        images: ['https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&q=80&w=800'],
        description: 'Detailed hand-painted resin footballer figure mounted on a marble-effect base. Gold and silver tiers available. Height 30cm. Free engraving plate included.',
        brand: 'SK Awards',
        category: trophy,
        price: 40.00,
        countInStock: 25,
        rating: 4.6,
        numReviews: 11,
      },
      {
        name: 'Cricket Glass Trophy',
        images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800'],
        description: 'Elegant full glass cricket-themed award featuring a cricket bat and ball motif. 20cm tall with a weighted black base. Supplied with personalised engraving in a gift box.',
        brand: 'SK Awards',
        category: trophy,
        price: 48.00,
        countInStock: 18,
        rating: 4.7,
        numReviews: 6,
      },
      {
        name: 'Spinning Wheel of Fortune Trophy',
        images: ['https://images.unsplash.com/photo-1587384474964-3a06ce1ce699?auto=format&fit=crop&q=80&w=800'],
        description: 'Unique spinning globe trophy made of die-cast metal with a brushed gold finish. Sits on a rosewood effect base, ideal for "Champion of Champions" awards.',
        brand: 'SK Awards',
        category: trophy,
        price: 75.00,
        countInStock: 10,
        rating: 5.0,
        numReviews: 4,
      },
      {
        name: 'Budget Medal Pack (Mixed, 50pcs)',
        images: ['https://images.unsplash.com/photo-1553778263-73a83bab9b0c?auto=format&fit=crop&q=80&w=800'],
        description: 'Pack of 50 mixed gold, silver and bronze medals on ribbons. Generic laurel and torch design, 50mm diameter. Perfect for schools, fun runs and grassroots tournaments.',
        brand: 'SK Awards',
        category: trophy,
        price: 45.00,
        countInStock: 200,
        rating: 4.2,
        numReviews: 33,
      },
    ];

    await Product.insertMany(products);

    console.log('✅ Data Imported Successfully! All categories seeded with 10+ products.');
    process.exit();
  } catch (error) {
    console.error(`❌ Seeder Error: ${error}`);
    process.exit(1);
  }
};

importData();
